name: flutter_event_calendar
description: Gregorian and Jalali Event calendar for flutter with options for change style
version: 0.0.7
homepage: https://github.com/faridfr/flutter_event_calendar

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  shamsi_date: ^0.15.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
